uw: 
  url: "https://ischool.uw.edu{query}"
  query: "/people/faculty"
  ischool: "University of Washington"
  faculty_selector: ".h1 > a"
  name_selector: "div > article > div.info > h1"
  title_selector: "div > article > div.info > em"
  email_selector: "div > article > div.info > address > a"
  spec_selector: ".sections > .specialization > ul > li"
  research_selector: ".sections > .research_areas > ul > li"
  bio_selector: ".sections > .biography"
  edu_selector: ".sections > .education > ul > li"
  pub_selector: ".pub > .title"
  class: "uw"

um:
  url: "https://www.si.umich.edu{query}"
  query: "/people/directory/faculty?page={n}"
  ischool: "University of Michigan"
  faculty_selector: "div > div > div > h2 > a"
  name_selector: "div > div > div > h1 > span"
  title_selector: "div > div > div > div > div > div.profile-card__left > span:nth-child(1) > strong"
  email_selector: "div > div > div > div > div > div.profile-card__left > span > a"
  phd_selector: "div > div > div > div > div > div.profile-card__right > span:nth-child(3)"
  research_selector: "div > div > div > div > ul > li"
  bio_selector: "div > div > div > div > div > p"
  edu_selector: "div > div > div > div > div > p"
  class: "um"

illinois:
  url: "https://ischool.illinois.edu{query}"
  query: "/people/faculty"
  faculty_selector: "div.profile-teaser__name > a"
  ischool: "University of Illinois Urban Champagne"
  name_selector: "#page-title > span"
  title_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > p.profile__title"
  email_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > div.profile__contact-information > p:nth-child(3)"
  phone_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > div.profile__contact-information > p:nth-child(2) > a"
  research_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > div.tag-list > ul > li > a"
  bio_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > div:nth-child(7) > div > p:nth-child(1)"
  edu_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > p.profile__education"
  pub_selector: "body > div.dialog-off-canvas-main-canvas > main > div > div.basic-page__guttered-content > div.basic-page__main > div > article > div > div.profile__core-content > div:nth-child(10) > div > p"
  delay: 2
  class: "illinois"

berkeley: 
  url: "https://www.ischool.berkeley.edu{query}"
  query: "/people?role=122&faculty_type=72"
  ischool: "University of California, Berkeley"
  faculty_selector: "div.views-field.views-field-field-profile-fullname > h2 > a"
  name_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-header > div.details > h1"
  title_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-header > div.details > h2"
  email_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-contact-info > div > div.user-contact-info-primary > div.field.field--name-field-profile-email.field--type-text.field--label-hidden > div > div > a"
  phone_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-contact-info > div > div.user-contact-info-primary > div.field.field--name-field-profile-telephone.field--type-telephone.field--label-hidden > div > div > a"
  spec_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-focus > div"
  research_selector: "#main-content > div > div.center-wrapper > div.panel-col-first.panel-panel > div > div.panel-pane.pane-user-research-areas > div > div > div > a"
  pub_selector: "#main-content > div > div.center-wrapper > div.panel-col-last.panel-panel > div > div.panel-pane.pane-views-panes.pane-user-publications-panel-pane-1 > div > div > div > div > span > a"
  class: "berkeley"

ut: 
  url: "https://www.ischool.utexas.edu{query}"
  query: "/people/ischool-faculty-staff-students"
  ischool: "University of Texas, Austin"
  faculty_selector: ".ppl_container > a"
  name_selector: ".basic_info > h2"
  title_selector: ".basic_info > .position:nth-child(3)"
  email_selector: ".basic_info > div > p > a:nth-child(2)"
  research_selector: "div > div > div > div > p"
  bio_selector: "div > div > div > div:nth-child(4)"
  edu_selector: "div > div > div > div"
  pub_selector: ".dcpt_part > .bibliography_cite"
  class: "ut"

unc:
  url: "https://sils.unc.edu{query}"
  query: "/directory/faculty"
  ischool: "University of North Carolina"
  faculty_selector: "div.views-field.views-field-title > span > a"
  name_selector: "#page-title"
  title_selector: "div > div.field.field-name-field-faculty-title.field-type-text.field-label-hidden.view-mode-full > div > div"
  email_selector: "div.field.field-name-field-faculty-email-address.field-type-email.field-label-hidden.view-mode-full > div > div"
  phone_selector: "div.field.field-name-field-faculty-phone.field-type-text.field-label-hidden.view-mode-full > div > div"
  research_selector: "div > section > div > div"
  edu_selector: "div > div.field.field-name-body.field-type-text-with-summary.field-label-hidden.view-mode-full > div > div > p:nth-child(1)"
  bio_selector: "div > div.field.field-name-body.field-type-text-with-summary.field-label-hidden.view-mode-full > div > div > p:nth-child(2)"
  course_selector: "div > div.field.field-name-body.field-type-text-with-summary.field-label-hidden.view-mode-full > div > div > p:nth-child(3)"
  class: "unc"

syracuse:
  url: "https://ischool.syr.edu"
  query: "/directory/"
  ischool: "Syracuse University"
  faculty_selector: "h5 > a"
  name_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-1.hero.bg-lt-gray.branded-corners.blue-headline.blue-text.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div > div > div.fusion-text > h1"
  title_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-1.hero.bg-lt-gray.branded-corners.blue-headline.blue-text.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div > div > div.fusion-text > h5:nth-child(2)"
  phone_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-1.hero.bg-lt-gray.branded-corners.blue-headline.blue-text.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div > div > div.fusion-text > h5:nth-child(4)"
  email_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-1.hero.bg-lt-gray.branded-corners.blue-headline.blue-text.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div > div > div.fusion-text > h5:nth-child(5)"
  course_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-2.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div.fusion-layout-column.fusion_builder_column.fusion_builder_column_2_3.fusion-builder-column-2.fusion-two-third.fusion-column-last.\32 _3 > div > div.fusion-text > ul > li"
  bio_selector: "div > div.fusion-fullwidth.fullwidth-box.fusion-builder-row-2.nonhundred-percent-fullwidth.non-hundred-percent-height-scrolling > div > div.fusion-layout-column.fusion_builder_column.fusion_builder_column_2_3.fusion-builder-column-2.fusion-two-third.fusion-column-last.\32 _3 > div > div.fusion-text > p"